apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: dnginx
  name: dnginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dnginx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: dnginx
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
