apiVersion: apps/v1
kind: Deployment 
metadata:
  name: nginx-deployment 
  labels:
    app: nginx
    team: frontend
spec:
  replicas: 3
  selector:
    matchLabels: 
      app: nginx
  template:
    metadata: 
      labels: 
        app: nginx
    spec:
      containers:
      - name: container1
        image: nginx
        imagePullPolicy: IfNotPresent