apiVersion: kyverno.io/v1
kind: ClusterPolicy 
metadata:
    name: require-deployment-team-label
spec:
    validationFailureAction: Enforce
    rules:
      - name: check-for-team-label
        match:
          any:
            - resources:
                kinds:
                 - Deployment
        validate:
           message: "The label 'team' is required for all deployments."
           pattern:
             metadata:
               labels:
                 team: "?*"
